### ISSUE TITLE
Clean CLI inputs

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#12]
Spaces and special characters should be cleaned on wizard inputs

**Comment by bboynton97** [comment]
@will-wright-eng

**Comment by bboynton97** [comment]
Handled partially by #13. Validation is a good idea as mentioned in #16

**Comment by HowieG** [comment]
+1. Should replace spaces with underscores when expecting snake_case

<img width="649" alt="Screenshot 2024-10-24 at 4 45 26 PM" src="https://github.com/user-attachments/assets/1d50f913-0368-4199-99db-590d905aa18b">
