### ISSUE TITLE
Dynamically load model providers

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#2]
In the agent wizard section of the CLI, it asks to enter the model and provider for the agent to use.

Any provider/model that works in LiteLLM should be accepted.

Import or create a list of all acceptable providers and associated models.

In the AgentWizard, ask the user to select the provider (show top 5 most common, then an other option that shows all).
After selecting the provider, ask them which model.

The associated provider/model should be stored in the agent datatype as a string with format `provider/model`

**Comment by Gitstar-OC** [comment]
Will try to work on this issue as a part of interview process along with some others,
