### ISSUE TITLE
environment variables not captured

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#41]
when adding env vars to .env in the project, the project is not finding them even after calling load_dotenv()

**Comment by bboynton97** [comment]
still receiving reports from users with this issue. it's unclear if this is an agentstack problem or users not knowledgable with `load_dotenv()`. i need to investigate further

**Comment by tcdent** [comment]
I did notice that some of the tools have a `load_dotenv` call at the top of their import, so maybe the repeated call is contributing to this? 

Shouldn't be removing variables from the ENV regardless. 

This may also be related to the path they're being loaded from? dotenv loads `~/.env` first if it finds it by default if I remember correctly. We could hardcode the project root path into our internal call.

**Comment by tcdent** [comment]
Ok, I think what's happening is that if the user has a `~/.env` file that is getting loaded first, and the project `.env` is skipped. We now explicitly load the project's environment variables and pass them to the run task. 

This will be released in the next version of agentstack and is available right now in the main branch. Feel free to reopen this issue if you are still experiencing problems.
