### ISSUE TITLE
Consultation regarding the purpose of the code under the `templetes/crewai/tools` directory.

### ISSUE THREAD

**Issue by chgaowei** [AgentOps-AI/AgentStack#53]
Are the codes in the `templetes/crewai/tools` directory meant to serve only as implementation references, or will they be directly invoked by the LLM? I made some adjustments to the tool interfaces earlier. Should we update the corresponding code in the `tools` directory each time, or is it sufficient to remove the code and use comments instead?

**Comment by bboynton97** [comment]
The code in `templates/crewai/tools` is the code that is copied into the developer's project when running `agentstack tools add <name>` and using the crewai framework.

When working on a tool, the code in the `<name>_tool.py` file is the final code that the user is given. Sometimes this is commented with ways in which the developer can configure the code to better suit their use case or with instructions on how to extend it!

Does this answer your question? :)
