### ISSUE TITLE
create a required format for tool configs

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#58]
At the moment, tool configs are json files with no format validation.

For example, some tools have `"tools_bundled": true,` and some do not.

We should make a required format and have a test that loops through each tool config and verifies that it is formatted properly. Because testing is performed before merge, this verifies that tool configurations will never break the CLI.

**Comment by bboynton97** [comment]
@dsfaccini i usually find using pydantic really hinders the development cycle, but this project may be getting to the scale of complexity that it only makes sense to use it

**Comment by dsfaccini** [comment]
Sounds good! I'll make a PR for this. Just cloned the repo and tried installing the dependencies, I'm on Ubuntu (Windows 11 WSL 2) and got an error installing psutil 

```log
Failed to download and build `psutil==5.9.0`
error: command 'clang' failed: No such file or directory
```

upping it to 6.1 fixed it, I'll include that in the PR
https://pypi.org/project/psutil/

**Comment by bboynton97** [comment]
ill merge in #64 and then if there's useful overlap ill merge #65 :)
thank you for the contribution @dsfaccini!!
