### ISSUE TITLE
Tasks not added to crew.py

### ISSUE THREAD

**Issue by jeremypeters** [AgentOps-AI/AgentStack#63]
e.g. `agentstack g t scrape_site` updates `tasks.yaml`, but not `crew.py`.

**Comment by bboynton97** [comment]
Thank you for the issue! This was fixed in the last release! Be sure to run `pip install --update agentstack` if you're still running into this :)

**Comment by vincent38wargnier** [comment]
Hi, have you published the last version cause I can't get it?
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f3151285-d20f-4ec4-b0b9-48510df2029b">

Thanks :)
