### ISSUE TITLE
check for update

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#66]
when running a command, check if on the latest version of agentstack
we're moving really fast and a number of support questions ive gotten would have been avoided if they were up to date

open to discussion if we're afraid this may slow down the CLI

**Comment by bboynton97** [comment]
@tcdent your thoughts appreciated

**Comment by tcdent** [comment]
throwing an auto-update at the top is super standard these days. 

just have to be cautious about backwards-incompatible changes.

**Comment by tcdent** [comment]
Released this with 0.2
