### ISSUE TITLE
Task definition is not created in crew.py

### ISSUE THREAD

**Issue by vanetreg** [AgentOps-AI/AgentStack#74]
Watching you web_scraper project video on Loom at:
https://www.loom.com/share/68d796b13cd94647bd1d7fae12b2358e?sid=7fdf595b-de84-4d51-9a81-ef1e9c8ac71c
after using command
`agentstack g t scrape_site`
no tool definition is created in crew.py

Tested in Windsurf v1.0.5
**Python 3.12.7.
AgentStack version: 0.1.13**

**Comment by bboynton97** [comment]
hi @vanetreg! thank you for the issue! there is a fix ready in the upcoming release. we have a _ton_ of updates coming in that release as well so it's been a little slow to get out the door.

In the meantime for the next day or so, if you add `# Task definitions` under the agent definitions in `crew.py` it will fix this issue. Alternatively, you can install via github `pip install https://github.com/AgentOps-AI/AgentStack.git`

**Comment by vanetreg** [comment]
I've added definition manually
