### ISSUE TITLE
Template Export

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#85]
As of version 0.2, AgentStack now supports initializing a project based on a template.

- Template formats should be enforced with Pydantic, much like the tool configs.
- A completed project should be exportable as a template. `agentstack template create`
  - creates a new .json file as `<project_name>.json`

Theoretically, someone could export the template from one framework and then re-init with a different framework. Lets build this with the assumption that we will follow up with a framework conversion feature. The demand is unclear but technically it doesn't seem like a difficult challenge.

**Comment by tcdent** [comment]
deployed in #118
